version: '3.8'
services:
  trembao-db:
    container_name: trembao-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=trembao_db
    ports:
      - 3308:3306
    volumes:
      - db:/var/lib/mysql
  backend:
    container_name: trembao-backend
    depends_on:
      - trembao-db
    build: ./backend
    environment:
      - PORT=4000
      - DB_USER=root
      - DB_HOST=trembao-db
      - DB_PASS=password
      - DB_NAME=trembao_db
      - JWT_SECRET=secret
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
    # volumes:
    #   - ./backend:/app
  frontend:
    container_name: trembao-frontend
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    # volumes:
    #   - ./frontend:/app
volumes: 
  db:

  ## Volumes backs up data from containers